# Generated by Django 4.2.4 on 2023-08-30 12:29
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def assign_blog_permissions(apps, schema_migration):
    # ensure that permissions have been created
    emit_post_migrate_signal(verbosity=1, interactive=False, db='default')

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_blog = Permission.objects.get(codename='add_blog')
    change_blog = Permission.objects.get(codename='change_blog')
    delete_blog = Permission.objects.get(codename='delete_blog')
    view_blog = Permission.objects.get(codename='view_blog')

    creator_permissions = [
        add_blog,
        change_blog,
        delete_blog,
        view_blog,
    ]

    creators = Group.objects.get(name='creators')
    for permission in creator_permissions:
        creators.permissions.add(permission)

    subscribers = Group.objects.get(name='subscribers')
    subscribers.permissions.add(view_blog)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20230830_1341'),
    ]

    operations = [
        migrations.RunPython(assign_blog_permissions)
    ]
