# Generated by Django 4.2.4 on 2023-08-31 14:45

from django.db import migrations, models


def remove_existing_self_follow(apps, schema_editor):
    Follow = apps.get_model("authentication", "Follow")
    db_alias = schema_editor.connection.alias
    Follow.objects.using(db_alias).filter(from_user=models.F("to_user")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_follow_user_follows_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=remove_existing_self_follow,
            reverse_code=migrations.RunPython.noop,
            elidable=True
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('from_user', models.F('to_user')), _negated=True),
                                              name='authentication_follow_prevent_self_follow'),
        ),
    ]
