# Generated by Django 4.2.4 on 2023-08-30 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_word_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('change_blog_title', "Peut changer le titre d'un billet de blog")]},
        ),
    ]
