# Generated by Django 4.2.4 on 2023-08-30 14:49
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def migrate_author_to_contributors(apps, schema_editor):
    emit_post_migrate_signal(verbosity=1, interactive=False, db='default')

    Blog = apps.get_model('blog', 'Blog')

    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(blog.author, through_defaults={'contributions': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author_blogcontributor_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors)
    ]
